# Generated by Django 5.1.1 on 2024-12-09 23:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
