# Generated by Django 5.1.1 on 2024-12-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0002_grade_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='grade',
            name='graded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
