# Generated by Django 5.1.1 on 2024-12-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0003_remove_grade_timestamp_grade_graded_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='message',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='course',
        ),
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Untitled Announcement', max_length=100),
            preserve_default=False,
        ),
    ]
