# Generated by Django 5.1.1 on 2024-12-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auapp', '0004_rename_message_announcement_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Untitled Announcement', max_length=100),
        ),
    ]
